apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: vahiwe.com
    http:
      paths:
      - path:
        backend:
          serviceName: devops-capstone-lb
          servicePort: 8000