apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-lb
  labels:
    app: devops-capstone
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone
  ports:
    - port: 8000
      targetPort: 8000