apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: udacity.project.vahiwe.com
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone
  ports:
    - port: 80
      targetPort: 8000